Add spaces to silence weird sign-conversion error
Assuming this is a bug on the compiler side
error: conversion to ‘long unsigned int’ from ‘long int’ may change the sign of the result [-Werror=sign-conversion]